version: '3.8'

services:
  # Test database
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cebeuygun_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d cebeuygun_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Test Redis
  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Test services
  auth-service-test:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - DB_HOST=postgres-test
      - DB_PORT=5432
      - DB_NAME=cebeuygun_test
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - REDIS_URL=redis://redis-test:6379
      - JWT_SECRET=test-jwt-secret
      - PORT=8001
    ports:
      - "8001:8001"
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order-service-test:
    build:
      context: ./services/order
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - DB_HOST=postgres-test
      - DB_PORT=5432
      - DB_NAME=cebeuygun_test
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - REDIS_URL=redis://redis-test:6379
      - AUTH_SERVICE_URL=http://auth-service-test:8001
      - PORT=8003
    ports:
      - "8003:8003"
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      auth-service-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway for testing
  nginx-test:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/test.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service-test
      - order-service-test

volumes:
  postgres_test_data:
  redis_test_data:

networks:
  default:
    name: cebeuygun-test
    driver: bridge