apiVersion: v2
name: cebeuygun-platform
description: A Helm chart for CebeUygun e-commerce platform
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: 19.x.x
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled

maintainers:
  - name: CebeUygun Platform Team
    email: platform@cebeuygun.com

keywords:
  - ecommerce
  - microservices
  - food-delivery
  - kubernetes