global:
  imageRegistry: ghcr.io
  imagePullSecrets:
    - name: ghcr-secret
  storageClass: "fast-ssd"

# Service configurations
services:
  auth:
    enabled: true
    image:
      repository: cebeuygun/auth-service
      tag: "latest"
      pullPolicy: IfNotPresent
    replicaCount: 3
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 20
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    service:
      type: ClusterIP
      port: 8001
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rate-limit: "100"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: api.cebeuygun.com
          paths:
            - path: /auth
              pathType: Prefix
      tls:
        - secretName: api-cebeuygun-com-tls
          hosts:
            - api.cebeuygun.com

  order:
    enabled: true
    image:
      repository: cebeuygun/order-service
      tag: "latest"
    replicaCount: 5
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    autoscaling:
      enabled: true
      minReplicas: 5
      maxReplicas: 30
      targetCPUUtilizationPercentage: 70

  payment:
    enabled: true
    image:
      repository: cebeuygun/payment-service
      tag: "latest"
    replicaCount: 3
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 15
      targetCPUUtilizationPercentage: 70

  courier:
    enabled: true
    image:
      repository: cebeuygun/courier-service
      tag: "latest"
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  notification:
    enabled: true
    image:
      repository: cebeuygun/notification-service
      tag: "latest"
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  reporting:
    enabled: true
    image:
      repository: cebeuygun/reporting-service
      tag: "latest"
    replicaCount: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

  integration:
    enabled: true
    image:
      repository: cebeuygun/integration-gateway
      tag: "latest"
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "secure-postgres-password"
    database: "cebeuygun"
  primary:
    persistence:
      enabled: true
      size: 100Gi
      storageClass: "fast-ssd"
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: true
    password: "secure-redis-password"
  master:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "fast-ssd"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

# Observability
observability:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
    adminPassword: "admin123"
  jaeger:
    enabled: true
  elasticsearch:
    enabled: true

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.cebeuygun.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-cebeuygun-com-tls
      hosts:
        - api.cebeuygun.com

# Security settings
security:
  networkPolicies:
    enabled: true
  podSecurityStandards:
    enabled: true
    enforce: "restricted"
  serviceAccounts:
    automountToken: false